version: '2.1'

services:
  # Your existing Redis service
  redis:
    container_name: redis
    image: redis:6.2-alpine
  
  # app
  app:
    container_name: app
    build: ./app
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    restart: always

  celery_worker:
    container_name: celery_worker
    build: ./app
    command: celery -A worker.celery_app worker --beat --loglevel=info --
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER=${CELERY_RESULT_BACKEND}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
  
  flower:
    container_name: flower
    build: ./app
    command: celery -A worker.celery_app flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - app
      - redis
      - celery_worker

