version: "3.7"

services:

  redis:
    container_name: redis
    image: redis:6.2-alpine
    networks:
      #testing_net:
      #  ipv4_address: 172.28.1.2
      - api-network

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - "./app:/app"
    environment:
      - CASSANDRA_IP_ADDRESS=cas1
      - CASSANDRA_KEYSPACE=roy      
    depends_on:
      - cas1
    ports:
      - 8000:8000
    networks:
      # testing_net:
      #   ipv4_address: 172.28.1.3
      - api-network

  cas1:
    container_name: cas1
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks:
      #testing_net:
      #  ipv4_address: 172.28.1.4
      - api-network

  cas2:
    container_name: cas2
    image: cassandra:latest
    ports:
      - 9043:9042
    depends_on:
      - cas1
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_SEEDS=cas1
    networks:
      #testing_net:
      #  ipv4_address: 172.28.1.5
      - api-network

  celery_worker:
    container_name: celery_worker
    build: ./app
    command: celery -A worker.celery_app worker --beat --loglevel=info --
    volumes:
      - ./app:/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CASSANDRA_IP_ADDRESS=cas1
    networks:
      # testing_net:
      #   ipv4_address: 172.28.1.6
      - api-network

    depends_on:
      - app
      - redis
      - cas1
        

  flower:
    container_name: flower
    build: ./app
    command: celery -A worker.celery_app flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

    networks:
      #testing_net:
      #  ipv4_address: 172.28.1.7
      - api-network

    depends_on:
      - app
      - redis
      - celery_worker

networks:
  api-network:
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.28.0.0/16
    driver: bridge
    name: api-network
